In [ ]:
#!pip install peft optuna scikit-learn tensorboard

Requirement already satisfied: peft in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (0.18.0)
Requirement already satisfied: optuna in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (4.6.0)
Requirement already satisfied: scikit-learn in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (1.7.2)
Requirement already satisfied: tensorboard in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (2.20.0)
Requirement already satisfied: numpy>=1.17 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from peft) (2.3.5)
Requirement already satisfied: packaging>=20.0 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from peft) (25.0)
Requirement already satisfied: psutil in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from peft) (7.1.3)
Requirement already satisfied: pyyaml in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from peft) (6.0.3)
Requirement already satisfied: torch>=1.13.0 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from peft) (2.9.1)
Requirement already satisfied: transformers in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from peft) (4.57.3)
Requirement already satisfied: tqdm in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from peft) (4.67.1)
Requirement already satisfied: accelerate>=0.21.0 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from peft) (1.12.0)
Requirement already satisfied: safetensors in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from peft) (0.7.0)
Requirement already satisfied: huggingface_hub>=0.25.0 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from peft) (0.36.0)
Requirement already satisfied: alembic>=1.5.0 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from optuna) (1.17.2)
Requirement already satisfied: colorlog in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from optuna) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from optuna) (2.0.44)
Requirement already satisfied: scipy>=1.8.0 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: absl-py>=0.4 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from tensorboard) (2.3.1)
Requirement already satisfied: grpcio>=1.48.2 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from tensorboard) (1.76.0)
Requirement already satisfied: markdown>=2.6.8 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from tensorboard) (3.10)
Requirement already satisfied: pillow in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from tensorboard) (12.0.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from tensorboard) (6.33.2)
Requirement already satisfied: setuptools>=41.0.0 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from tensorboard) (80.9.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from tensorboard) (3.1.4)
Requirement already satisfied: Mako in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: filelock in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from huggingface_hub>=0.25.0->peft) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from huggingface_hub>=0.25.0->peft) (2025.10.0)
Requirement already satisfied: requests in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from huggingface_hub>=0.25.0->peft) (2.32.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from huggingface_hub>=0.25.0->peft) (1.2.0)
Requirement already satisfied: greenlet>=1 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from sqlalchemy>=1.4.2->optuna) (3.3.0)
Requirement already satisfied: sympy>=1.13.3 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (3.6)
Requirement already satisfied: jinja2 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (1.13.1.3)
Requirement already satisfied: triton==3.5.1 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from torch>=1.13.0->peft) (3.5.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: markupsafe>=2.1.1 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from requests->huggingface_hub>=0.25.0->peft) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from requests->huggingface_hub>=0.25.0->peft) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from requests->huggingface_hub>=0.25.0->peft) (2.6.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from requests->huggingface_hub>=0.25.0->peft) (2025.11.12)
Requirement already satisfied: regex!=2019.12.17 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from transformers->peft) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /home/onyxia/work/venv_sa/lib/python3.13/site-packages (from transformers->peft) (0.22.1)

In [3]:
import numpy as np
import evaluate
import torch
from datasets import load_dataset
import csv
from transformers import (
    AutoTokenizer, 
    AutoModelForSequenceClassification, 
    TrainingArguments, 
    Trainer,
    EarlyStoppingCallback # Pour arrêter si ça ne s'améliore plus (Monitoring/Efficiency)
)
from peft import LoraConfig, get_peft_model, TaskType # Pour l'efficacité (LoRA)

# --- Configuration ---
MODEL_CHECKPOINT = "bert-base-uncased"
NUM_LABELS = 6
BATCH_SIZE = 16

/home/onyxia/work/venv_sa/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
# Chargement (Votre code original fonctionnait très bien ici)
col_names = [
    "id", "label_text", "statement", "subject", "speaker", 
    "job_title", "state_info", "party_affiliation", 
    "barely_true_counts", "false_counts", "half_true_counts", 
    "mostly_true_counts", "pants_on_fire_counts", "context"
]

raw_datasets = load_dataset(
    "csv", 
    data_files={
        "train": "/home/onyxia/work/Stat_App/Data/train.tsv", 
        "validation": "/home/onyxia/work/Stat_App/Data/valid.tsv", 
        "test": "/home/onyxia/work/Stat_App/Data/test.tsv"
    }, 
    delimiter="\t", column_names=col_names, quoting=csv.QUOTE_NONE
)

# Mapping Labels
label_mapping = {'pants-fire': 0, 'false': 1, 'barely-true': 2, 'half-true': 3, 'mostly-true': 4, 'true': 5}
raw_datasets = raw_datasets.map(lambda x: {'label': label_mapping[x['label_text']]})

# Tokenization
tokenizer = AutoTokenizer.from_pretrained(MODEL_CHECKPOINT)
def tokenize_function(example):
    return tokenizer(example["statement"], truncation=True, padding="max_length", max_length=128)

tokenized_datasets = raw_datasets.map(tokenize_function, batched=True)
tokenized_datasets.set_format("torch", columns=["input_ids", "attention_mask", "label"])

Map: 100%|██████████| 10269/10269 [00:01<00:00, 8458.19 examples/s]
Map: 100%|██████████| 1284/1284 [00:00<00:00, 7668.33 examples/s]
Map: 100%|██████████| 1283/1283 [00:00<00:00, 7306.29 examples/s]
Map: 100%|██████████| 10269/10269 [00:00<00:00, 10631.60 examples/s]
Map: 100%|██████████| 1284/1284 [00:00<00:00, 8569.94 examples/s]
Map: 100%|██████████| 1283/1283 [00:00<00:00, 8454.68 examples/s]

In [5]:
# Chargement des métriques
accuracy_metric = evaluate.load("accuracy")
f1_metric = evaluate.load("f1")
precision_metric = evaluate.load("precision")
recall_metric = evaluate.load("recall")

def compute_metrics(eval_preds):
    logits, labels = eval_preds
    predictions = np.argmax(logits, axis=-1)
    
    # Calcul de toutes les métriques
    accuracy = accuracy_metric.compute(predictions=predictions, references=labels)
    
    # 'weighted' prend en compte le déséquilibre des classes
    f1 = f1_metric.compute(predictions=predictions, references=labels, average="weighted")
    precision = precision_metric.compute(predictions=predictions, references=labels, average="weighted")
    recall = recall_metric.compute(predictions=predictions, references=labels, average="weighted")
    
    return {
        "accuracy": accuracy["accuracy"],
        "f1": f1["f1"],
        "precision": precision["precision"],
        "recall": recall["recall"]
    }

Downloading builder script: 6.79kB [00:00, 6.10MB/s]
Downloading builder script: 7.56kB [00:00, 6.32MB/s]
Downloading builder script: 7.38kB [00:00, 4.11MB/s]

In [6]:
# Fonction d'initialisation du modèle (nécessaire pour Optuna plus tard)
def model_init():
    # 1. Charger le modèle de base
    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_CHECKPOINT, 
        num_labels=NUM_LABELS
    )
    
    # 2. Configuration LoRA (Parameter-Efficient Fine-Tuning)
    peft_config = LoraConfig(
        task_type=TaskType.SEQ_CLS, 
        inference_mode=False, 
        r=8,            # Rang de la matrice (plus petit = plus léger)
        lora_alpha=16, 
        lora_dropout=0.1
    )
    
    # 3. Appliquer LoRA au modèle
    model = get_peft_model(model, peft_config)
    
    # Affiche le % de paramètres entraînables (souvent < 1%)
    model.print_trainable_parameters()
    
    return model

In [ ]:
training_args = TrainingArguments(
    output_dir="liar-bert-lora-finetuned",
    
    # --- Efficiency ---
    gradient_checkpointing=True,  # Économise beaucoup de VRAM
    fp16=True,                    # Utilise la précision mixte (plus rapide sur GPU)
    
    # --- Monitoring ---
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_steps=50,             # Log plus fréquent pour voir la courbe
    report_to="tensorboard",      # Active le suivi
    load_best_model_at_end=True,
    metric_for_best_model="f1",   # On optimise le F1, pas juste l'accuracy
    
    # --- Standard ---
    learning_rate=2e-4,           # LoRA supporte des taux plus élevés que le fine-tuning classique
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    num_train_epochs=3,           # On peut augmenter car c'est plus rapide
    weight_decay=0.01,
    save_total_limit=1            # Économie d'espace disque
)

In [10]:
trainer = Trainer(
    model_init=model_init,        # On passe la fonction, pas le modèle instancié
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)] # Arrête si pas d'amélioration après 2 époques
)

def hp_space(trial):
    return {
        "learning_rate": trial.suggest_float("learning_rate", 1e-5, 5e-4, log=True),
        "per_device_train_batch_size": trial.suggest_categorical("per_device_train_batch_size", [16, 32]),
    }

best_run = trainer.hyperparameter_search(
    direction="maximize", 
    backend="optuna", 
    hp_space=hp_space, 
    n_trials=5  # Tester 5 combinaisons différentes
)
print(f"Meilleurs paramètres trouvés : {best_run.hyperparameters}")

# Appliquer les meilleurs paramètres pour l'entraînement final
for n, v in best_run.hyperparameters.items():
    setattr(trainer.args, n, v)


# Entraînement Final
trainer.train()

/tmp/ipykernel_12751/3203344984.py:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

trainable params: 299,526 || all params: 109,786,380 || trainable%: 0.2728

[I 2025-12-07 11:15:22,714] A new study created in memory with name: no-name-95fa8a76-06cf-43af-ba14-923060dd8321
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

trainable params: 299,526 || all params: 109,786,380 || trainable%: 0.2728

/home/onyxia/work/venv_sa/lib/python3.13/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(

/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
[I 2025-12-07 11:16:50,791] Trial 0 finished with value: 0.5953220297608954 and parameters: {'learning_rate': 2.5363827034569217e-05, 'per_device_train_batch_size': 16}. Best is trial 0 with value: 0.5953220297608954.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

trainable params: 299,526 || all params: 109,786,380 || trainable%: 0.2728

/home/onyxia/work/venv_sa/lib/python3.13/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(

/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
[I 2025-12-07 11:18:08,190] Trial 1 finished with value: 0.6180651799353366 and parameters: {'learning_rate': 3.8848967440166875e-05, 'per_device_train_batch_size': 32}. Best is trial 1 with value: 0.6180651799353366.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

trainable params: 299,526 || all params: 109,786,380 || trainable%: 0.2728

/home/onyxia/work/venv_sa/lib/python3.13/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(

/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
[I 2025-12-07 11:19:25,895] Trial 2 finished with value: 0.704244050797862 and parameters: {'learning_rate': 0.00011711565349759347, 'per_device_train_batch_size': 32}. Best is trial 2 with value: 0.704244050797862.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

trainable params: 299,526 || all params: 109,786,380 || trainable%: 0.2728

/home/onyxia/work/venv_sa/lib/python3.13/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(

/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
[I 2025-12-07 11:20:55,035] Trial 3 finished with value: 0.61639861743397 and parameters: {'learning_rate': 1.4289128512947146e-05, 'per_device_train_batch_size': 16}. Best is trial 2 with value: 0.704244050797862.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

trainable params: 299,526 || all params: 109,786,380 || trainable%: 0.2728

/home/onyxia/work/venv_sa/lib/python3.13/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(

/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
[I 2025-12-07 11:22:11,341] Trial 4 finished with value: 0.625471419657433 and parameters: {'learning_rate': 2.559976128166712e-05, 'per_device_train_batch_size': 32}. Best is trial 2 with value: 0.704244050797862.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Meilleurs paramètres trouvés : {'learning_rate': 0.00011711565349759347, 'per_device_train_batch_size': 32}
trainable params: 299,526 || all params: 109,786,380 || trainable%: 0.2728

/home/onyxia/work/venv_sa/lib/python3.13/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(

/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

TrainOutput(global_step=963, training_loss=1.7618985735614971, metrics={'train_runtime': 75.0779, 'train_samples_per_second': 410.334, 'train_steps_per_second': 12.827, 'total_flos': 2033575066156032.0, 'train_loss': 1.7618985735614971, 'epoch': 3.0})

In [11]:
print("--- Évaluation Complète sur Test ---")
test_results = trainer.evaluate(tokenized_datasets["test"])
print(test_results)

--- Évaluation Complète sur Test ---

{'eval_loss': 1.7422270774841309, 'eval_accuracy': 0.21590023382696805, 'eval_f1': 0.11850862071317726, 'eval_precision': 0.12082558772507987, 'eval_recall': 0.21590023382696805, 'eval_runtime': 2.6743, 'eval_samples_per_second': 479.758, 'eval_steps_per_second': 30.289, 'epoch': 3.0}

/home/onyxia/work/venv_sa/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])